trigger:
- master

pool:
  name: Default

stages:
  - stage: Setup
    displayName: 'Setup tools'
    jobs:
      - job: SetupNodeAndMoon
        displayName: 'Install Node.js and Moon'
        pool:
          name: Default
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - script: |
              npm install -g @moonrepo/cli
            displayName: 'Install moon'

          - script: |
              node -v
              npm -v
            displayName: 'Check Node.js and npm versions'

  - stage: InstallDependencies
    displayName: 'Install dependencies for projects'
    dependsOn: Setup
    jobs:
      - job: InstallProjectA
        displayName: 'Install dependencies for project-a'
        pool:
          name: Default
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Ensure Node.js is installed'
            
          - script: |
              cd apps/project-a
              npm install
            displayName: 'Install dependencies for project-a'

      - job: InstallProjectB
        displayName: 'Install dependencies for project-b'
        pool:
          name: Default
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Ensure Node.js is installed'
            
          - script: |
              cd apps/project-b
              npm install
            displayName: 'Install dependencies for project-b'

  - stage: Build
    displayName: 'Build projects'
    dependsOn: InstallDependencies
    jobs:
      - job: BuildProjects
        displayName: 'Build project-a and project-b'
        pool:
          name: Default
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Ensure Node.js is installed'

          - script: |
              moon run project-a:build project-b:build
            displayName: 'moon run projects build'
