trigger:
- master

pool:
  name: Default

stages:
  - stage: Setup
    displayName: 'Setup tools'
    jobs:
      - job: SetupTools
        displayName: 'Install Node.js and tools'
        pool:
          name: Default
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - script: |
              npm install -g @moonrepo/cli vue-cli-service react react-scripts
            displayName: 'Install Moon, Vue CLI, and React Scripts'

  - stage: InstallDependencies
    displayName: 'Install dependencies for projects'
    dependsOn: Setup
    jobs:
      - job: InstallProjectA
        displayName: 'Install dependencies for project-a'
        pool:
          name: Default
        steps:
          - task: NodeTool@0 # required to avoid npm context issue
            inputs:
              versionSpec: '18.x'
            displayName: 'Setup Node.js for project-a'
          - script: |
              cd apps/project-a
              npm ci
            displayName: 'Install dependencies for project-a'

      - job: InstallProjectB
        displayName: 'Install dependencies for project-b'
        pool:
          name: Default
        steps:
          - task: NodeTool@0 # required to avoid npm context issue
            inputs:
              versionSpec: '18.x'
            displayName: 'Setup Node.js for project-b'
          - script: |
              cd apps/project-b
              npm ci
            displayName: 'Install dependencies for project-b'

  - stage: Build
    displayName: 'Build projects'
    dependsOn: InstallDependencies
    jobs:
      - job: BuildProjects
        displayName: 'Build project-a and project-b'
        pool:
          name: Default
        steps:
          - task: NodeTool@0 # required to avoid npm context issue
            inputs:
              versionSpec: '18.x'
            displayName: 'Setup Node.js for Build'
          - script: |
              moon run project-a:build project-b:build
            displayName: 'moon run projects build'
