trigger:
- master

pool:
  name: Default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @moonrepo/cli
  displayName: 'Install moon'

- script: |
    cd apps/project-a
    npm install
  displayName: 'Install dependencies for project-a'

- script: |
    cd apps/project-b
    npm install
  displayName: 'Install dependencies for project-b'

- script: |
    moon run project-a:build project-b:build
  displayName: 'moon run projects build'
