trigger:
- master

pool:
  name: Default

stages:
  - stage: Setup
    displayName: 'Setup tools and install dependencies'
    jobs:
      - job: SetupTools
        displayName: 'Install node.js, moon, react and vue.js'
        pool:
          name: Default
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - script: |
              npm install -g @moonrepo/cli
              npm install -g vue-cli-service
              npm install -g react-scripts
            displayName: 'Install Moon, Vue CLI, and React Scripts'

  - stage: InstallDependencies
    displayName: 'Install dependencies for projects'
    dependsOn: Setup
    jobs:
      - job: InstallDeps
        displayName: 'Install dependencies for projects'
        pool:
          name: Default
        steps:
          - script: |
              cd apps/project-a
              npm install
            displayName: 'Install dependencies for project-a'

          - script: |
              cd apps/project-b
              npm install
            displayName: 'Install dependencies for project-b'

  - stage: Build
    displayName: 'Build projects'
    dependsOn: InstallDependencies
    jobs:
      - job: BuildProjects
        displayName: 'Build project-a and project-b'
        pool:
          name: Default
        steps:
          - script: |
              moon run project-a:build project-b:build
            displayName: 'moon run projects build'
