trigger:
- master

pool:
  name: Default

stages:
  - stage: Setup
    displayName: 'Setup tools'
    jobs:
      - job: SetupTools
        displayName: 'Install Node.js and Moon'
        pool:
          name: Default
        steps:
          - script: |
              echo "Cleaning up temp directory..."
              rm -rf /home/ubuntu/azure_agent/_work/_temp/*
            displayName: 'Clean temp directory'

          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - script: |
              npm cache clean --force
              npm install -g @moonrepo/cli
            displayName: 'Install Moon'

  - stage: InstallDependencies
    displayName: 'Install dependencies for projects'
    dependsOn: Setup
    jobs:
      - job: InstallProjectA
        displayName: 'Install dependencies for project-a'
        pool:
          name: Default
        steps:
          - script: |
              cd apps/project-a
              npm ci
            displayName: 'Install dependencies for project-a'

      - job: InstallProjectB
        displayName: 'Install dependencies for project-b'
        pool:
          name: Default
        steps:
          - script: |
              cd apps/project-b
              npm ci
            displayName: 'Install dependencies for project-b'

  - stage: Build
    displayName: 'Build projects'
    dependsOn: InstallDependencies
    jobs:
      - job: BuildProjectA
        displayName: 'Build Project A'
        pool:
          name: Default
        steps:
          - script: |
              cd apps/project-a
              moon run project-a:build 
            displayName: 'Build project-a with Moon'

      - job: BuildProjectB
        displayName: 'Build Project B'
        pool:
          name: Default
        steps:
          - script: |
              cd apps/project-b
              moon run project-b:build 
            displayName: 'Build project-b with Moon'
