trigger:
- master

pool:
  name: Default

stages:
  - stage: Setup
    displayName: 'Setup tools'
    jobs:
      - job: SetupTools
        displayName: 'Install tools'
        pool:
          name: Default
        steps:
          # Clean up the temp directory before installation
          - script: |
              echo "Cleaning up temp directory..."
              rm -rf /home/ubuntu/azure_agent/_work/_temp/*
            displayName: 'Clean temp directory'

          # Install Node.js
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'
            
          # Add a step to print the Node.js and npm version to verify installation
          - script: |
              node -v
              npm -v
            displayName: 'Verify Node.js and npm installation'

          # Install Moon
          - script: |
              npm install -g @moonrepo/cli
            displayName: 'Install Moon'

  - stage: InstallDependencies
    displayName: 'Install dependencies for projects'
    dependsOn: Setup
    jobs:
      - job: InstallProjectA
        displayName: 'Install dependencies for project-a'
        pool:
          name: Default
        steps:
          # Verify Node.js and npm availability
          - script: |
              node -v
              npm -v
            displayName: 'Verify Node.js and npm installation for project-a'
          
          - script: |
              cd apps/project-a
              npm ci
            displayName: 'Install dependencies for project-a'

      - job: InstallProjectB
        displayName: 'Install dependencies for project-b'
        pool:
          name: Default
        steps:
          # Verify Node.js and npm availability
          - script: |
              node -v
              npm -v
            displayName: 'Verify Node.js and npm installation for project-b'
          
          - script: |
              cd apps/project-b
              npm ci
            displayName: 'Install dependencies for project-b'

  - stage: Build
    displayName: 'Build projects'
    dependsOn: InstallDependencies
    jobs:
      - job: BuildProjects
        displayName: 'Build project-a with Moon'
        pool:
          name: Default
        steps:
          # Verify Node.js and npm availability
          - script: |
              node -v
              npm -v
            displayName: 'Verify Node.js and npm installation for Build'
          
          - script: |
              moon run project-a:build 
            displayName: 'moon run project-a build'
